### ISSUE TITLE
Dashlane AutoPKG Recipe currently not working 

### ISSUE THREAD

**Issue by jcbousfield** [autopkg/joshua-d-miller-recipes#125]
Hey,  

I am running your AutoPKG recipe to download Dashlane, however I am being presented with the following output from the autoPKG run... 

```
`Processing com.github.joshua-d-miller.download.dashlane...
WARNING: com.github.joshua-d-miller.download.dashlane is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.4.1',
 'NAME': 'Dashlane',
 'PACKAGE_OUTPUT_DIR': '/Users/jamesb/Library/CloudStorage/OneDrive-MoofIT/Documents '
                       '- Packages/Packages',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/jamesb/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.dashlane',
 'RECIPE_DIR': '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes/Dashlane',
 'RECIPE_OVERRIDE_DIRS': ['/Users/jamesb/GitHub/autopkg_overrides/'],
 'RECIPE_PATH': '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes/Dashlane/Dashlane.download.recipe',
 'RECIPE_REPOS': {'/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.Yohan460-recipes': {'URL': 'https://github.com/autopkg/Yohan460-recipes'},
                  '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes'},
                  '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes': {'URL': 'https://github.com/autopkg/moofit-recipes'},
                  '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes': {'URL': 'https://github.com/autopkg/novaksam-recipes'},
                  '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/jamesb/Library/AutoPkg/RecipeRepos/com.github.autopkg.Yohan460-recipes'],
 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) '
               'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.94 '
               'Safari/537.36 Vivaldi/2.6.1566.40',
 'verbose': 4}
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>https:\\/\\/.*.cloudfront\\.net\\/releases\\/.*\\/.*\\/Dashlane\\.dmg)',
           'url': 'https://ws1.dashlane.com/5/binaries/query?format=json&os=OS_X_10_14_5&target=archive&platform=launcher_macosx'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://ws1.dashlane.com/5/binaries/query?format=json&os=OS_X_10_14_5&target=archive&platform=launcher_macosx']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://ws1.dashlane.com/5/binaries/query?format=json&os=OS_X_10_14_5&target=archive&platform=launcher_macosx
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://ws1.dashlane.com/5/binaries/query?format=json&os=OS_X_10_14_5&target=archive&platform=launcher_macosx
Failed.
Receipt written to /Users/jamesb/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.dashlane/receipts/com.github.joshua-d-miller.download-receipt-20220628-150411.plist

The following recipes failed:
    com.github.joshua-d-miller.download.dashlane
        Error in com.github.joshua-d-miller.download.dashlane: Processor: URLTextSearcher: Error: No match found on URL: https://ws1.dashlane.com/5/binaries/query?format=json&os=OS_X_10_14_5&target=archive&platform=launcher_macosx

Nothing downloaded, packaged or imported.
`
```

Thank you!

**Comment by jcbousfield** [comment]
Appears to have been converted to an extension rather than an Application FYI

**Comment by joshua-d-miller** [comment]
It appears to also be an application but they may have gone App Store only with this one. I have reached out to DashLane to ask if they will still be providing a download link for the app outside the App Store.

**Comment by joshua-d-miller** [comment]
Unfortunately the response I got back from Dashlane is that it appears to be an App Store only application now and since that is the case, you could deploy it with your favorite MDM using Volume Purchasing. I'll be removing this recipe as it is now longer relevant. I apologize for the inconvenience this may cause.
