### ISSUE TITLE
Evernote.download.recipe - No match found on URL

### ISSUE THREAD

**Issue by blackthroat** [autopkg/joshua-d-miller-recipes#94]
Either the Evernote file naming convention changed or this is a one-off situation. I suspect this is causing the `re_pattern` not to find a match.

https://cdn1.evernote.com/boron/mac/builds/Evernote-10.6.9-mac-ddl-ga-2254.dmg

```URLTextSearcher
{'Input': {'re_pattern': '(?P<url>https:\\/\\/cdn1\\.evernote\\.com\\/boron\\/mac\\/builds\\/Evernote-[\\d.]+-[\\d]+\\.dmg)',
           'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
                                             'Mac OS X 11_0_0) '
                                             'AppleWebKit/537.36 (KHTML, like '
                                             'Gecko) Chrome/86.0.4240.193 '
                                             'Safari/537.36 Edg/86.0.622.68'},
           'url': 'https://evernote.com/download'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://evernote.com/download
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
No match found on URL: https://evernote.com/download
Failed.
```

**Comment by blackthroat** [comment]
Resolved with https://github.com/autopkg/joshua-d-miller-recipes/commit/e4ef5d6da9c2b748aae314e752a04baccabc96ef

Thanks!
